name: piano
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - audioread==3.0.1
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - decorator==5.2.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.183.0
      - google-auth==2.41.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - httplib2==0.31.0
      - idna==3.10
      - joblib==1.5.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.43.0
      - mido==1.3.3
      - msgpack==1.1.1
      - numba==0.60.0
      - numpy==2.0.2
      - packaging==25.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - pretty-midi==0.2.10
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - requests==2.32.5
      - rsa==4.9.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - urllib3==2.5.0
prefix: /home/dwu/miniconda3/envs/piano
